// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzqkhomoeoihxlqokeek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6cWtob21vZW9paHhscW9rZWVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzUxNTQsImV4cCI6MjA3Mzc1MTE1NH0.kHDnLhGuWff5O562ic4hcCSw3_qQAbk3_JkF5kTjDAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});